apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: blue-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: blue-frontend
    app.kubernetes.io/part-of: blue-whale
  name: blue-frontend
  namespace: pdave3
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: blue-frontend
status:
  loadBalancer: {}
